name: 'Webhook on Merge'
on:
  pull_request:
    types: [closed]

jobs:
  run: # make sure the action works on a clean machine without building
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: Teamwork/mobile-versioning-action
      - uses: ./
