name: 'On Merge'
on: workflow_dispatch
  # pull_request:
  #   types: [closed]

jobs:
  run: # make sure the action works on a clean machine without building
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./
