name: 'build'
if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #     - run: |
  #         npm run all

  # run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./
